# Build customization
builds:
  - id: main
    goos:
      - darwin
      - linux
    goarch:
      - 386
      - amd64
      - arm
      - arm64
      - mips
    gomips:
      - softfloat

release:
  github:
    owner: utilitywarehouse
    name: wiresteward

archives:
  - builds:
      - main
    format: binary
    files:
      - none*

brews:
  - name: wiresteward
    description: Wireguard peer manager
    license: MIT
    folder: Formula
    tap:
      owner: utilitywarehouse
      name: homebrew-tap
    test:
      system "#{bin}/wiresteward", "-version"
    install: |-
      bin.install "wiresteward"
