# Build customization
version: 2
builds:
  - id: main
    goos:
      - darwin
      - linux
    goarch:
      - 386
      - amd64
      - arm
      - arm64
      - mips
    gomips:
      - softfloat

release:
  github:
    owner: utilitywarehouse
    name: wiresteward

archives:
  - builds:
      - main
    format: binary
    files:
      - none*

brews:
  - name: wiresteward
    description: Wireguard peer manager
    homepage: https://github.com/utilitywarehouse/wiresteward
    license: MIT
    directory: Formula
    repository:
      owner: utilitywarehouse
      name: homebrew-tap
