# Build customization
builds:
  - id: main
    goos:
      - darwin
      - linux
    goarch:
      - 386
      - amd64
      - arm
      - arm64
      - mips
    gomips:
      - softfloat

release:
  github:
    owner: utilitywarehouse
    name: wiresteward

archives:
  - builds:
      - main
    format: binary
    files:
      - none*

brews:
  - name: wiresteward
    description: Wireguard peer manager
    homepage: https://github.com/utilitywarehouse/wiresteward
    license: MIT
    folder: Formula
    tap:
      owner: utilitywarehouse
      name: homebrew-tap
    caveats: |
      *********************
      When running the agent via `brew services` place your config file at `/etc/wiresteward/config.json`
      *********************
      To start the agent run:
        brew services start utilitywarehouse/tap/wiresteward
      To stop the agent run:
        brew services stop utilitywarehouse/tap/wiresteward
      To restart the agent run:
        brew services restart utilitywarehouse/tap/wiresteward
      *********************
      To uninstall the agent run the following commands:
        brew services stop utilitywarehouse/tap/wiresteward
        brew uninstall utilitywarehouse/tap/wiresteward
        launchctl remove uk.co.uw.wiresteward
      *********************
    plist: |
      <?xml version="1.0" encoding="UTF-8"?>
      <!DOCTYPE plist PUBLIC "-/Apple/DTD PLIST 1.0/EN" "http:/www.apple.com/DTDs/PropertyList-1.0.dtd">
      <plist version="1.0">
        <dict>
          <key>Label</key>
          <string>uk.co.uw.wiresteward</string>

          <key>KeepAlive</key>
          <true/>

          <key>RunAtLoad</key>
          <true/>

          <key>ProgramArguments</key>
          <array>
            <string>#{bin}/wiresteward</string>
            <string>-agent</string>
          </array>

          <key>StandardErrorPath</key>
          <string>/var/log/wiresteward.err.log</string>

          <key>StandardOutPath</key>
          <string>/var/log/wiresteward.log</string>
        </dict>
      </plist>
