name: Go tests

on:
  push:
    tags:
      - "*"
  pull_request:
  schedule:
    - cron: "0 10 * * *" # daily at 10:00 UTC
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
      - uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
      - uses: geomys/sandboxed-step@v1.2.1
        with:
          run: |
            go test -v ./...
